site_name: 'SRO Knowledgebase'
site_description: 'SRO Knowledgebase and documentation'
site_author: 'Southampton Robotics Outreach'
site_url: 'https://kb.roboticsoutreach.org'

repo_name: 's-r-o/kb'
repo_url: 'https://github.com/s-r-o/kb'

theme:
  name: 'material'
  logo: 'img/sro_logo_arm.svg'
  favicon: 'img/favicon.ico'
  language: 'en'
  feature:
    tabs: true
  palette:
    primary: 'light blue'
    accent: 'light blue'
  font:
    text: 'Source Sans Pro'
    code: 'Inconsolata'
extra:
  manifest: 'app.manifest'  
  social:
    - type: github
      link: 'https://github.com/s-r-o'
    - type: facebook-square
      link: 'https://facebook.com/SROSoton'
    - type: slack
      link: 'https://sourcebots.slack.com'
  
copyright: 'Copyright &copy; Southampton Robotics Outreach.'

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - meta
  - attr_list
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

